name: Generate merged JSON

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-merged-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          bb: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: mkdir generated
      - run: bb scripts/generate-merged-json.bb a5e
      - run: bb scripts/generate-merged-json.bb sns
      - uses: actions/upload-artifact@v4
        with:
          name: sns.json
          path: generated/sns.json
      - uses: actions/upload-artifact@v4
        with:
          name: a5e.json
          path: generated/a5e.json
